---
- hosts: "{{ host }}"
  tasks:
  - name: Install Depencies
    yum: name={{ item }} state=present
    with_items:
      - openssl-devel
      - openssl
      - libffi-devel
      - MySQL-python
      - mysql-devel

  - name: Download Python3
    command: wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz

  - name: Extract Python3
    command: tar -zxvf Python-3.7.2.tgz

  - name: Install Python3
    command: "{{ item }} chdir=/root/Python-3.7.2/"
    with_items:
        - ./configure
        - make -j 8
        - make install
  
  - name: clean Up
    command: "{{item}} chdir=/root/"
    with_items:
        - rm -f Python-3.7.2.tgz
        - rm -rf Python-3.7.2

