---
-
  hosts: "{{ host }}"
  tasks:
    - name: Install imply
      command: "{{ item }}"
      with_items:
        - wget https://static.imply.io/release/imply-2.8.14.tar.gz
        - mkdir -p /opt/bigdata
        - tar zxvf /root/imply-2.8.14.tar.gz -C /opt/bigdata
        - mv /opt/bigdata/imply-2.8.14 /opt/bigdata/imply
        - rm -rf /root/imply-2.8.14.tar.gz
      tags:
        - t1

    - name: Copy configure
      copy:
        src: "{{conf_dir}}/common.runtime.properties"
        dest: /opt/bigdata/imply/conf/druid/_common
      tags:
        - cpconf

    - name: start master
      shell: /opt/bigdata/imply/bin/supervise -c /opt/bigdata/imply/conf/supervise/master-no-zk.conf
      async: 999999999
      poll: 0
      tags:
        - smaster

    - name: start data server
      shell: /opt/bigdata/imply/bin/supervise -c /opt/bigdata/imply/conf/supervise/data.conf
      async: 999999999
      poll: 0
      tags:
        - sdata

    - name: start query server
      shell: /opt/bigdata/imply/bin/supervise -c /opt/bigdata/imply/conf/supervise/query.conf
      async: 999999999
      poll: 0
      tags:
        - squery






